name: flutter_gutierrez_garcia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # UUID para ID únicos
  uuid: ^4.3.1

  # Base de datos local
  sqflite: ^2.3.2
  path: ^1.8.3
  shared_preferences: ^2.2.2

  # Cloudinary
  cloudinary_flutter: ^1.0.0
  cloudinary_url_gen: ^1.0.0

  # HTTP para subir archivos
  http: ^0.13.6

  # Picker de imágenes
  image_picker: ^1.0.7

  # Gestión de estado
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/

  # fonts:
  #   - family: MyFont
  #     fonts:
  #       - asset: fonts/MyFont-Regular.ttf
